name: tcv

on:
  push:
    branches:
      - '*'
      - 'Saurabhkr952-patch-1'

jobs:
  t:
    name:  test
    runs-on: ubuntu-latest
    steps: 
      - name: Download Artifact
        run: echo "Hello"
