name: workflow test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Dependencies for Tests
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest --cov=tests --cov-report=xml --junitxml=test_results.xml
      
     #     coverage run -m pytest
   #       pytest --junitxml=test_result.xml
          
          # pytest --junitxml=test_result.xml

      - name: Generate coverage report
        run: coverage xml -o /home/runner/work/temp-replication/temp-replication/test_result.xml     
          # Separate coverage report generation if using coverage package
        #  coverage xml -o /home/runner/work/temp-replication/temp-replication/test_result.xml
      - name: Print Coverage File
        run: cat /home/runner/work/temp-replication/temp-replication/test_result.xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: /home/runner/work/temp-replication/temp-replication/test_result.xml
        
