name: workflow test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Dependencies for Tests
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        continue-on-error: true
        run: |
          pytest tests --junit-xml test-results/pytest.xml
      #    coverage run -m pytest tests
  
      - name: generate coverage report
        continue-on-error: true
        run: |
          pytest --cov=. --cov-report=xml
          cat coverage.xml

      - name: upload result
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_ORGANIZATION_PROVIDER: gh
          CODACY_USERNAME: Saurabhkr952
          CODACY_PROJECT_NAME: temp-replication
          CODACY_REPORTER_VERSION: 13.13.15
          # 13.13.8
          CODACY_REPORTER_SKIP_CHECKSUM: false
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
#      - name: Run codacy-coverage-reporter
#        uses: codacy/codacy-coverage-reporter-action@v1
#        with:
#          project-token: ${{ secrets.CODACY_API_TOKEN }}
#          coverage-reporter-version: 13.13.8

        
        
