name: workflow test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Dependencies for Tests
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests --junit-xml test-results/pytest.xml
          cat test-results/pytest.xml
     #     coverage run -m pytest
   #       pytest --junitxml=test_result.xml
          
          # pytest --junitxml=test_result.xml

           
          # Separate coverage report generation if using coverage package
        #  coverage xml -o /home/runner/work/temp-replication/temp-replication/test_result.xml

      - name: generate coverage report
        run: |
          pytest --cov=. --cov-report=json
#          cat coverage.xml
        
#      - name: upload result
#        env:
#          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
#          CODACY_ORGANIZATION_PROVIDER: gh
#          CODACY_USERNAME: Saurabhkr952
#          CODACY_PROJECT_NAME: temp-replication
#        run: |
#          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.json
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.json
        
