name: workflow test

on:
  push:
    branches:
      - main
jobs:      
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Installing Dependencies for Tests
        run: |
          ls -ltra
          pip install --upgrade pip && pip install -r requirements.txt

      - name: Execute Tests
        run: pytest tests/test.py --junit-xml test-results/pytest.xml

      - name: list files
        run: ls -ltra
