name: workflow test

on:
  push:
    branches:
      - main
jobs:      
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Installing Dependencies for Tests
        run: |
          ls -ltra
          pip install --upgrade pip && pip install -r requirements.txt

      - name: Execute Tests
        continue-on-error: true
        run: |
          pytest tests/test.py --junit-xml test-results/result.xml


      - name: list files
        run: ls -ltra
        
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: jZ9emG9EiMhkPNRExwHX
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: test-results/result.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
