name: workflow test

on:
  push:
    branches:
      - main
jobs:      
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Installing Dependencies for Tests
        run: |
          ls -ltra
          pip install --upgrade pip && pip install -r requirements.txt

      - name: Execute Tests
        continue-on-error: true
        run: |
          pytest --junit-xml test-results/pytest.xml
          pytest tests/test.py --junitxml=test-results/result.xml
       #   pytest tests/test.py --junit-xml test-results/result.xml

      - name: upload result
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_ORGANIZATION_PROVIDER: gh
          CODACY_USERNAME: Saurabhkr952
          CODACY_PROJECT_NAME: temp-replication
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l python -r test-results/result.xml 
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: 927a7b5e6cc14e3894e26ac1c80a0b55
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: test-results/result.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
